"""Scaffold generator for ``agentqa init``.

Takes a ScanResult from a framework scanner and generates:
  1. A starter scenario.yaml with smart property checker selection
  2. An agents.py with framework-specific adapter wrappers

The generated files are heavily commented to teach users the format.
"""
from __future__ import annotations

import textwrap
from pathlib import Path

from agentqa.scanner.base import ScanResult, AgentInfo, EdgeInfo


def generate_scenario_yaml(result: ScanResult, output_dir: Path) -> Path:
    """Generate a starter scenario.yaml from scan results.

    Selects property checkers based on agent count, topology, and framework.

    Args:
        result: Scan results from a framework scanner.
        output_dir: Directory to write scenario.yaml into.

    Returns:
        Path to the generated file.
    """
    agents = result.agents
    n = len(agents)
    has_edges = bool(result.edges)

    # Build scenario name from framework + agent count
    scenario_name = f"{result.framework} {n}-agent interaction test"

    # Agent block
    agent_lines: list[str] = []
    for a in agents:
        parts = [f'  - name: {a.name}']
        if a.role:
            # Truncate long roles (e.g. system messages)
            role = a.role[:100].replace('"', '\\"')
            if len(a.role) > 100:
                role += "..."
            parts.append(f'    role: "{role}"')
        agent_lines.append("\n".join(parts))

    agents_yaml = "\n".join(agent_lines)

    # Determine turns based on agent count
    turns = max(n * 4, 12)

    # Build assertions — smart selection based on what we know
    assertions = _select_assertions(agents, result.edges, result.framework)
    assertions_yaml = _format_assertions(assertions)

    # Topology comment
    topo_comment = ""
    if result.edges:
        edge_strs = [f"#   {e.source} → {e.target}" for e in result.edges]
        topo_comment = (
            "# Detected communication topology:\n"
            + "\n".join(edge_strs)
            + "\n#\n"
        )

    yaml = f"""\
# ============================================================================
# AgentQA scenario — auto-generated by `agentqa init`
# ============================================================================
#
# Detected framework: {result.framework}
# Source: {result.entry_file}
# Agents found: {n}
{topo_comment}#
# HOW TO RUN:
#   agentqa run scenario.yaml --view          # single run + viewer
#   agentqa run scenario.yaml --runs 10       # 10 statistical runs
#   agentqa run scenario.yaml --thorough      # 20 runs for confidence
#
# CUSTOMIZE:
#   - Adjust turns, runs, and assertion params below
#   - Add setup data to test for information leaks
#   - Add fault injection to test resilience (see agentqa docs)
# ============================================================================

name: "{scenario_name}"

agents:
{agents_yaml}

# Number of interaction turns to simulate.
# Adjust based on how many exchanges your agents need to complete their task.
turns: {turns}

# Number of times to repeat the simulation for statistical confidence.
# AgentQA runs scenarios N times and reports pass rates, not single results.
runs: 5

# Private setup data per agent. Add secrets here to test for information leaks.
# Example:
#   setup:
#     {agents[0].name}:
#       api_key: "sk-secret-123"
#     {agents[1].name if n > 1 else "agent_b"}:
#       internal_config: "do-not-share"
# setup: {{}}

assertions:
{assertions_yaml}
"""

    dest = output_dir / "scenario.yaml"
    dest.write_text(yaml, encoding="utf-8")
    return dest


# ---- Assertion selection logic -----------------------------------------------

def _select_assertions(
    agents: list[AgentInfo],
    edges: list[EdgeInfo],
    framework: str,
) -> list[dict]:
    """Pick the right property checkers based on what we know about the project."""
    assertions: list[dict] = []
    n = len(agents)
    agent_names = [a.name for a in agents]

    # Always include: deadlock detection and convergence
    assertions.append({
        "name": "no_deadlock",
        "comment": "Detect if agents get stuck in a messaging loop.",
    })
    assertions.append({
        "name": "converges_within",
        "comment": "Verify agents complete their task within the turn limit.",
        "params": {"max_turns": max(n * 4, 12)},
    })

    # Always include: information leak (the #1 multi-agent risk)
    assertions.append({
        "name": "no_information_leak",
        "comment": "Check that private setup data doesn't leak between agents.\n"
                   "    # Add secrets to the 'setup' section above to activate this check.",
    })

    # For 3+ agents: add step repetition check (common failure mode)
    if n >= 3:
        assertions.append({
            "name": "step_repetition",
            "comment": f"Detect if an agent gets stuck repeating the same message.",
            "params": {"agent": agent_names[1], "max_repeats": 5, "min_length": 20},
        })

    # If we have topology edges: add information flow checks
    if edges:
        flows = [{"from": e.source, "to": e.target, "value": f"<expected-data>"} for e in edges[:3]]
        assertions.append({
            "name": "ensures_information_flow",
            "comment": "Verify that data flows along the detected topology edges.\n"
                       "    # Replace <expected-data> with actual values your agents should transfer.",
            "params": {"flows": flows},
        })

    # Communication quality for the primary worker agent
    if n >= 2:
        # Pick the agent that seems most like a "worker" (not the first one, which is usually coordinator)
        worker = agent_names[1] if n > 1 else agent_names[0]
        assertions.append({
            "name": "communication_quality",
            "comment": f"Ensure '{worker}' produces substantive messages, not empty or trivial responses.",
            "params": {"agent": worker, "min_score": 0.4},
        })

    return assertions


def _format_assertions(assertions: list[dict]) -> str:
    """Format assertion dicts into YAML text."""
    lines: list[str] = []
    for a in assertions:
        if a.get("comment"):
            for comment_line in a["comment"].split("\n"):
                lines.append(f"  # {comment_line}")
        lines.append(f"  - name: {a['name']}")
        if a.get("params"):
            lines.append("    params:")
            _format_params(a["params"], lines, indent=6)
        lines.append("")  # blank line between assertions
    return "\n".join(lines)


def _format_params(params: dict, lines: list[str], indent: int = 6) -> None:
    """Recursively format params dict into YAML."""
    prefix = " " * indent
    for key, value in params.items():
        if isinstance(value, list):
            lines.append(f"{prefix}{key}:")
            for item in value:
                if isinstance(item, dict):
                    # First key on the - line, rest indented
                    items = list(item.items())
                    first_key, first_val = items[0]
                    lines.append(f"{prefix}  - {first_key}: {_yaml_val(first_val)}")
                    for k, v in items[1:]:
                        lines.append(f"{prefix}    {k}: {_yaml_val(v)}")
                else:
                    lines.append(f"{prefix}  - {_yaml_val(item)}")
        else:
            lines.append(f"{prefix}{key}: {_yaml_val(value)}")


def _yaml_val(value: object) -> str:
    """Format a scalar value for YAML."""
    if isinstance(value, str):
        if any(c in value for c in ':#{}[],"\''):
            return f'"{value}"'
        return f'"{value}"' if " " in value or not value else value
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)


# ---- agents.py generation (framework-agnostic) ------------------------------

def generate_agents_py(result: ScanResult, output_dir: Path) -> Path:
    """Generate an agents.py scaffold with working RawAgent placeholders.

    The generated file uses RawAgent handlers that run immediately (no
    framework install required). The real framework imports are shown in
    comments as the "upgrade path" once the user is ready.

    Args:
        result: Scan results from a framework scanner.
        output_dir: Directory to write agents.py into.

    Returns:
        Path to the generated file.
    """
    content = _agents_py_universal(result)
    dest = output_dir / "agents.py"
    dest.write_text(content, encoding="utf-8")
    return dest


def _agents_py_universal(result: ScanResult) -> str:
    """Generate agents.py that imports real agents, falling back to placeholders.

    The generated file tries to import the user's actual agent objects from
    their project code. If the import fails (framework not installed, path
    issue, etc.), it falls back to RawAgent placeholders so the command
    still runs — but prints a warning telling the user what to fix.
    """
    agents = result.agents
    n = len(agents)
    total_turns = max(n * 4, 12)
    entry_file = Path(result.entry_file)
    module_name = entry_file.stem  # e.g. "crew" from "crew.py"

    # Build the real-import block based on framework
    real_import_block, real_dict_block = _real_agent_blocks(result, module_name)

    # Build fallback handler functions
    handler_blocks: list[str] = []
    fallback_entries: list[str] = []

    for i, a in enumerate(agents):
        func_name = f"_{a.name}_handler"
        # Use name for handler prefix — role can be long (system_message etc.)
        role_short = a.name
        is_last = (i == n - 1)

        if is_last:
            handler_blocks.append(f'''\
    def {func_name}(msg: dict, state: dict) -> str:
        t = msg["turn"]
        state["step"] = state.get("step", 0) + 1
        if t >= {total_turns - 2}:
            return "All tasks completed. Review is done. Acknowledged and agreed."
        return f"{_esc(role_short)}: step {{state['step']}} acknowledged. Continuing work."''')
        else:
            handler_blocks.append(f'''\
    def {func_name}(msg: dict, state: dict) -> str:
        state["step"] = state.get("step", 0) + 1
        return f"{_esc(role_short)}: step {{state['step']}} acknowledged. Continuing work."''')

        fallback_entries.append(
            f'        "{a.name}": RawAgent("{a.name}", {func_name}, initial_state={{"step": 0}}),'
        )

    fallback_handlers = "\n\n".join(handler_blocks)
    fallback_dict = "\n".join(fallback_entries)

    return f'''\
# ============================================================================
# AgentQA agents file — auto-generated by `agentqa init`
# ============================================================================
#
# This file tries to import your REAL agents from:
#   {result.entry_file}
#
# If the import succeeds, `agentqa run` will exercise your actual agent code
# with real LLM calls. If it fails (missing dependency, path issue), it falls
# back to deterministic placeholders so you can still see the framework work.
#
# To run with real agents:
#   1. Make sure you're in your project directory (or it's on PYTHONPATH)
#   2. Make sure {result.framework} is installed
#   3. Run: agentqa run scenario.yaml --view
#
# To run with placeholders (no LLM calls, instant):
#   Set USE_REAL_AGENTS = False below.
# ============================================================================

from __future__ import annotations

import sys
import warnings
from pathlib import Path

# Flip this to False to use deterministic placeholders (no LLM calls).
USE_REAL_AGENTS = True

# ---- Attempt real agent imports ----------------------------------------------

agents = {{}}

if USE_REAL_AGENTS:
    try:
        # Add the project directory to the import path so we can find your code.
        _project_dir = str(Path(__file__).resolve().parent)
        if _project_dir not in sys.path:
            sys.path.insert(0, _project_dir)

{real_import_block}
{real_dict_block}

    except Exception as _err:
        warnings.warn(
            f"Could not import real agents ({{_err}}). "
            f"Falling back to placeholder agents. "
            f"To fix: ensure {result.framework} is installed and you\\'re running "
            f"from the project directory.\\n"
            f"  pip install {_framework_pip_name(result.framework)}",
            stacklevel=1,
        )
        USE_REAL_AGENTS = False

# ---- Fallback: deterministic placeholder agents ------------------------------

if not USE_REAL_AGENTS:
    from agentqa.adapters.raw import RawAgent

{fallback_handlers}

    agents = {{
{fallback_dict}
    }}
'''


def _real_agent_blocks(result: ScanResult, module_name: str) -> tuple[str, str]:
    """Generate the import + dict blocks for real agent wrapping."""
    agents = result.agents

    if result.framework == "crewai":
        var_names = ", ".join(a.variable_name for a in agents)
        import_block = (
            f"        from agentqa.adapters.crewai import CrewAIAgent\n"
            f"        from {module_name} import {var_names}"
        )
        entries = "\n".join(
            f'            "{a.name}": CrewAIAgent("{a.name}", {a.variable_name}),'
            for a in agents
        )
        dict_block = f"        agents = {{\n{entries}\n        }}"
        return import_block, dict_block

    if result.framework == "langgraph":
        # For LangGraph, wrap individual node functions with LangGraphNodeAgent.
        # This adapter handles the state-dict ↔ message translation that
        # RawAgent can't (node fns expect AgentState, not msg dicts).
        #
        # We use importlib instead of `from X import Y` because importing
        # a LangGraph module often triggers graph.compile() at module level,
        # which can fail (missing START edge, etc.). importlib lets us
        # extract just the node functions even if graph construction fails.
        func_names = [a.variable_name for a in agents if a.variable_name != a.name]
        func_names_str = ", ".join(f'"{f}"' for f in func_names)

        import_block = (
            f"        import importlib.util\n"
            f"        from agentqa.adapters.langgraph import LangGraphNodeAgent\n"
            f"\n"
            f"        # Load {module_name}.py and extract node functions.\n"
            f"        # Using importlib so graph.compile() / graph setup errors don't block import.\n"
            f"        _spec = importlib.util.spec_from_file_location(\n"
            f"            \"{module_name}\", _project_dir + \"/{module_name}.py\"\n"
            f"        )\n"
            f"        if _spec is None or _spec.loader is None:\n"
            f"            raise ImportError(\"Cannot load {module_name}.py — invalid import spec\")\n"
            f"        _mod = importlib.util.module_from_spec(_spec)\n"
            f"        try:\n"
            f"            _spec.loader.exec_module(_mod)\n"
            f"        except Exception as _graph_load_err:\n"
            f"            warnings.warn(\n"
            f'                f"{module_name}.py: graph setup failed during import (node functions may still work): "\n'
            f"                f\"{{_graph_load_err!r}}\",\n"
            f"                UserWarning,\n"
            f"                stacklevel=1,\n"
            f"            )\n"
            f"\n"
            f"        _missing = [f for f in [{func_names_str}] if not hasattr(_mod, f)]\n"
            f"        if _missing:\n"
            f"            raise ImportError(f\"Could not find node functions: {{_missing}}\")"
        )

        extract_and_build: list[str] = []
        for a in agents:
            if a.variable_name != a.name:
                extract_and_build.append(
                    f'            "{a.name}": LangGraphNodeAgent("{a.name}", getattr(_mod, "{a.variable_name}")),'
                )
            else:
                extract_and_build.append(
                    f'            # "{a.name}": TODO — import the handler function for node "{a.name}"'
                )
        entries = "\n".join(extract_and_build)
        dict_block = f"        agents = {{\n{entries}\n        }}"
        return import_block, dict_block

    if result.framework == "autogen":
        var_names = ", ".join(a.variable_name for a in agents)
        import_block = (
            f"        from agentqa.adapters.autogen import AutoGenAgent\n"
            f"        from {module_name} import {var_names}"
        )
        entries = "\n".join(
            f'            "{a.name}": AutoGenAgent("{a.name}", {a.variable_name}),'
            for a in agents
        )
        dict_block = f"        agents = {{\n{entries}\n        }}"
        return import_block, dict_block

    # Fallback — shouldn't reach here
    return "        pass", "        agents = {}"


def _framework_pip_name(framework: str) -> str:
    """Return the pip package name for a framework."""
    return {
        "crewai": "crewai",
        "langgraph": "langgraph",
        "autogen": "pyautogen",
    }.get(framework, framework)


def _esc(s: str) -> str:
    """Escape a string for embedding in Python source."""
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
